workflows:
  android-tools-debug:
    name: Macro Studio Android - APK debug
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Extraire et compiler Macro Studio Android
        script: |
          rm -rf source
          mkdir source
          unzip -q watch-apk-test-macro-studio-arm64.zip -d source
          cd source
          chmod +x gradlew
          ./gradlew assembleDebug
    artifacts:
      - source/app/build/outputs/apk/debug/app-debug.apk
